services:
  - type: web
    name: wowlogbook
    env: php
    plan: free
    buildCommand: |
      curl -s https://getcomposer.org/installer | php
      ./composer.phar install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
